version: '3'
services:
    mysql:
        image: mysql:8.0
        environment:
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
        ports:
            - '127.0.0.1:3306:3306'
        volumes:
            - mysql:/var/lib/mysql
    app:
        build: .
        ports:
            - '${PORT}:8000'
        environment:
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_USERNAME=root
            - DB_DATABASE=${DATABASE_NAME}
        volumes:
            - './app:/app'
volumes:
    mysql:
